routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\BranchController;
use App\Http\Controllers\ImageCropController;
use App\Http\Controllers\InstructorController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\IcsaStudentLoginController;
use App\Http\Controllers\IcsacourseController;
use App\Http\Controllers\IcsastudentController;
use App\Http\Controllers\IcsaregistrationController;

use App\Http\Controllers\SourceController;
use App\Http\Controllers\IcsabatchController;
use App\Http\Controllers\PaymentmethodController;
use App\Http\Controllers\IcsapaymentdetailController;
use App\Http\Controllers\IcsapaymentrefundController;
use App\Http\Controllers\ProspectgenerateLinkController;
use App\Http\Controllers\EmailTemplateController;
use App\Http\Controllers\AdscourseController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::redirect('/', '/login');
/*Route::get('/', function () {
    return view('welcome');
});*/



Auth::routes();
Route::impersonate();
Route::post('/login', [LoginController::class, 'authenticate']);
Route::post('/employee/login', [IcsaStudentLoginController::class, 'login'])->name('employee.login');


Route::group(['middleware' => ['auth']], function() {
   /* Route::get('/users/impersonate/{user_id}', [UserController::class, 'impersonate'])->name('users.impersonate');
    Route::get('/users/impersonate_leave', [UserController::class, 'impersonate_leave'])->name('impersonate.leave');*/

    Route::get('/changeRole/{id}', [UserController::class, 'changeRole'])->name('users.changeRole');
    Route::get('/changeBranch/{id}', [UserController::class, 'changeBranch'])->name('users.changeBranch');
    Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index']);

    Route::any('icsastudents/editenrollment', [IcsastudentController::class, 'editenrollment'])->name('icsastudents.editenrollment');
    Route::any('icsastudents/getenrolldetails', [IcsastudentController::class, 'getenrolldetails'])->name('icsastudents.getenrolldetails');

    Route::any('icsastudentsearch', [IcsastudentController::class, 'searchenroll'])->name('icsastudents.searchenroll');
    Route::any('icsapaymentsearch', [IcsapaymentdetailController::class, 'searchenroll'])->name('icsapayment.searchenroll');

    Route::get('icsapayment/addpayment', [IcsapaymentdetailController::class, 'addpayment'])->name('icsapayment.addpayment');
    Route::get('icsapayment/addpayment/{id}', [IcsapaymentdetailController::class, 'icsaaddpayment'])->name('icsapayment.icsaaddpayment');

    Route::get('icsapaymentrefund/refundpayment', [IcsapaymentrefundController::class, 'refundpayment'])->name('icsapayment.refundpayment');
    Route::get('icsapaymentrefund/refundpayment/{id}', [IcsapaymentrefundController::class, 'icsarefundpayment'])->name('icsapayment.icsarefundpayment');

    Route::get('icsapayment/printinvoice', [IcsapaymentdetailController::class, 'showinvoice'])->name('icsapayment.showinvoice');
    Route::get('icsapayment/printinvoice/{id}', [IcsapaymentdetailController::class, 'printinvoice'])->name('icsapayment.printinvoice');

    Route::any('icsapayment/getenrolldetails', [IcsapaymentdetailController::class, 'getenrolldetails'])->name('icsapayment.getenrolldetails');

    Route::resource('users',UserController::class);
    Route::resource('roles',RoleController::class);
    Route::resource('branch',BranchController::class);
    Route::resource('instructor',InstructorController::class);
    Route::resource('icsacourse',IcsacourseController::class);
    Route::resource('icsastudents',IcsastudentController::class);
    Route::resource('source',SourceController::class);
    Route::resource('icsabatch',IcsabatchController::class);
    Route::resource('paymentmethod',PaymentmethodController::class);

    Route::resource('icsapayment',IcsapaymentdetailController::class);
    Route::resource('icsapaymentrefund',IcsapaymentrefundController::class);

    Route::resource('adscourse',AdscourseController::class);
    Route::resource('emailtemplate',EmailTemplateController::class);

    Route::get('emailtemplate/attach/{id}', [EmailTemplateController::class, 'contentlist'])->name('emailtemplate.attach.content');

    Route::get('emailtemplate/attach/create/{id}', [EmailTemplateController::class, 'contentcreate'])->name('emailtemplate.attach.create');

    Route::post('emailtemplate/attach/store/{id}', [EmailTemplateController::class, 'contentstore'])->name('emailtemplate.attach.store');

    Route::get('emailtemplate/attach/{id}/edit/{template_id}', [EmailTemplateController::class, 'contentedit'])->name('emailtemplate.attach.edit');

    Route::PATCH('emailtemplate/attach/{id}/update/{template_id}', [EmailTemplateController::class, 'updatecontent'])->name('emailtemplate.attach.update');

    Route::get('emailtemplate/attach/{template_id}/{id}', [EmailTemplateController::class, 'contentshow'])->name('emailtemplate.attach.show');

    Route::delete('emailtemplate/attach/{id}/{template_id}', [EmailTemplateController::class, 'destroycontent'])->name('emailtemplate.attach.destroy');

    //Route::get('dropzone', [EmailTemplateController::class, 'dropzone']);
    Route::post('dropzone/store/{val}', [EmailTemplateController::class, 'dropzoneStore'])->name('dropzone.store');

    Route::post('icsastudents/getdetails', [IcsastudentController::class, 'getdetails'])->name('icsastudents.getdetails');

    /*Route::get('icsastudent/editenrollment', [IcsastudentController::class, 'editenrollment'])->name('icsastudent.editenrollment');*/



    Route::post('users/getdetails', [UserController::class, 'getdetails'])->name('users.getdetails');

    Route::post('image_crop/upload', [ImageCropController::class, 'upload'])->name('image_crop.upload');


    Route::get('generate/link', [ProspectgenerateLinkController::class, 'generateLinkPage'])->name('generate.link');
    Route::post('generate/link', [ProspectgenerateLinkController::class, 'generateLink'])->name('generate.linkshow');

    Route::get('/manager', function () {
        return 'hello Manager';
    })->name('manager');

});
Route::get('user', function()
{
    return View::make('pages.user');
});
Route::get('tables', function()
{
    return View::make('pages.tables');
});
Route::get('typography', function()
{
    return View::make('pages.typography');
});
Route::get('icons', function()
{
    return View::make('pages.icons');
});
Route::get('map', function()
{
    return View::make('pages.map');
});
Route::get('notifications', function()
{
    return View::make('pages.notifications');
});
Route::get('icsaregistrationform', function()
{
    return View::make('pages.icsaregistration.icsaregistrationform');
});

/*Route::get('icsaregistration', [IcsaregistrationController::class, 'index'])->name('icsaregistration.index');
Route::post('icsaregistration', [IcsaregistrationController::class, 'store'])->name('icsaregistration.store');*/

Route::resource('icsaregistration',IcsaregistrationController::class);

Route::post('icsaregistration/getbatches', [IcsaregistrationController::class, 'getbatches'])->name('icsaregistration.getbatches');

Route::post('icsaregistration/getcountrycode', [IcsaregistrationController::class, 'getcountrycode'])->name('icsaregistration.getcountrycode');

Route::get('refer/link/{user}/{course}/{branch}', [ProspectgenerateLinkController::class, 'referLink'])->name('refer.link');

resources/views/pages/prospect/generatelink.blade.php
@extends('layouts.default')
@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="pull-left">
                                        <h4 class="card-title ">ICSA Student Payment Details</h4>
                                        <p class="card-category"> All ICSA Students Payment.</p>
                                    </div>
                                    <div class="pull-right">
                                        @if(auth()->user()->canAccess('icsastudent-create'))
                                            <a style="padding: .54rem 2.14rem; margin-top: 0" class="btn btn-success"
                                               href="{{ route('icsastudents.create') }}"> Enroll New Student</a>
                                        @endif
                                    </div>
                                </div>
                            </div>
                            {!! Form::open(array('route' => 'generate.linkshow', 'method'=>'POST')) !!}
                            <br>
                            <div class="row">
                                <div class="col-xs-12 col-sm-12 col-md-3" style="">
                                    <div class="">
                                        {!! Form::select('frequency', [
                                        '' => 'Select Frequency',
                                        'crs' => 'Course Reservation'
                                        ], ($frequency ? $frequency : null), array('class' => 'form-control frequency','id' => 'frequency-select', 'required')) !!}
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-4" style="padding-left: 0">
                                    <div class="">
                                        {!! Form::select('course_id', $courses, ($course_id ? $course_id : null), array('class' => 'form-control course_id','', 'data-live-search="true"', 'data-style="btn-primary"','id' => 'course-select', 'required')) !!}
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-3" style="padding-left: 0">
                                    <div class="">
                                        {!! Form::select('branch_id', $branches, ($branch_id ? $branch_id : null), array('class' => 'form-control branch_id','', 'data-live-search="true"', 'data-style="btn-primary"','id' => 'branch-select', 'required')) !!}
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-1" style="padding-left: 0">
                                    <div class="">
                                        <button type="submit" style="padding: .54rem 2.14rem; margin-top: 0;"
                                                class="btn btn-primary" title="Search Data"><i class="fa fa-search"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                            {!! Form::close() !!}
                        </div>
                        @if($course_id != 'null')
                            <div class="card-body">
                                {{--<div class="input-group">
                                    <input class="col-sm-11" id="foo" type="text" value="{{ route('refer.link', ['user'=>auth()->user()->username, 'course'=> $course_id, 'branch'=>$branch_id]) }}">
                                    <span class="input-group-button">
      <button class="btn-lg" type="button" data-clipboard-demo="" data-clipboard-target="#foo">
        <img class="clippy" src="https://clipboardjs.com/assets/images/clippy.svg" width="13" alt="Copy to clipboard">
      </button>
    </span>
                                </div>--}}
                                <div class="contact">
                                    <div class="btn-group col-lg-12">
                                        <a class="col-lg-11 btn btn-primary btn-email" href="{{ route('refer.link', ['user'=>auth()->user()->username, 'course'=> $course_id, 'branch'=>$branch_id]) }}" target="_blank">{{ route('refer.link', ['user'=>auth()->user()->username, 'course'=> $course_id, 'branch'=>$branch_id]) }}</a>
                                        <button type="button" class="col-lg-1 btn btn-outline-primary btn-copy js-tooltip js-copy" data-toggle="tooltip" data-placement="bottom" data-copy="{{ route('refer.link', ['user'=>auth()->user()->username, 'course'=> $course_id, 'branch'=>$branch_id]) }}" title="Copy to clipboard">
                                            <!-- icon from google's material design library -->
                                            <img class="clippy" src="https://clipboardjs.com/assets/images/clippy.svg" width="23" alt="Copy to clipboard">
                                        </button>
                                    </div>
                                </div>
                                {{--{{ route('refer.link',['user'=>auth()->user()->username, 'branch'=> $course_id, 'course'=>$branch_id]) }}--}}
                               {{-- <a href="{{ route('refer.link', ['user'=>auth()->user()->username, 'course'=> $course_id, 'branch'=>$branch_id]) }}">Refer
                                    Link</a>--}}
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('custom-script')
    <script type="text/javascript">

        function copyToClipboard(text, el) {
            var copyTest = document.queryCommandSupported('copy');
            var elOriginalText = el.attr('data-original-title');

            if (copyTest === true) {
                var copyTextArea = document.createElement("textarea");
                copyTextArea.value = text;
                document.body.appendChild(copyTextArea);
                copyTextArea.select();
                try {
                    var successful = document.execCommand('copy');
                    var msg = successful ? 'Copied!' : 'Whoops, not copied!';
                    el.attr('data-original-title', msg).tooltip('show');
                } catch (err) {
                    console.log('Oops, unable to copy');
                }
                document.body.removeChild(copyTextArea);
                el.attr('data-original-title', elOriginalText);
            } else {
                // Fallback if browser doesn't support .execCommand('copy')
                window.prompt("Copy to clipboard: Ctrl+C or Command+C, Enter", text);
            }
        }

        $(document).ready(function() {
            // Initialize
            // ---------------------------------------------------------------------

            // Tooltips
            // Requires Bootstrap 3 for functionality
            $('.js-tooltip').tooltip();

            // Copy to clipboard
            // Grab any text in the attribute 'data-copy' and pass it to the
            // copy function
            $('.js-copy').click(function() {
                var text = $(this).attr('data-copy');
                var el = $(this);
                copyToClipboard(text, el);
            });
        });

        $(document).ready(function () {
            $('#course-select').selectpicker();
            $('#paymentod-select').selectpicker();

            $('#1, #2, #3, #4, #5, #6, #7, #8').DataTable({
                /* "columnDefs": [
                     { "orderable": false, "targets": 4 }
                 ]*/
                "bSort": false
            });
            //$('.dataTables_length').addClass('bs-select');
        });
        $(function () {
            // on init
            $(".table-hideable .hide-col").each(HideColumnIndex);

            // on click
            $('.hide-column').click(HideColumnIndex)

            function HideColumnIndex() {
                var $el = $(this);
                var $cell = $el.closest('th,td')
                var $table = $cell.closest('table')

                // get cell location - https://stackoverflow.com/a/4999018/1366033
                var colIndex = $cell[0].cellIndex + 1;

                // find and hide col index

                $table.find("tbody tr, thead tr")
                    .children(":nth-child(" + colIndex + ")")
                    .addClass('hide-col');
                $('.hide-col').hide();
                // show restore footer
                $table.find(".footer-restore-columns").show()
            }

            // restore columns footer
            $(".restore-columns").click(function (e) {
                $('.hide-col').show();

                var $table = $(this).closest('table')
                $table.find(".footer-restore-columns").hide()
                $table.find("th, td")
                    .removeClass('hide-col');

            });

            $('[data-toggle="tooltip"]').tooltip({
                trigger: 'hover'
            })

        })
    </script>
    <style>
        .table-hideable td,
        .table-hideable th {
            width: auto;
            transition: width .5s, margin .5s;
        }

        .btn-condensed.btn-condensed {
            padding: 0 5px;
            box-shadow: none;
        }

        /*.hide-col {
            width: 0px !important;
            height: 0px !important;
            display: block !important;
            overflow: hidden !important;
            margin: 0 !important;
            padding: 0 !important;
            border: none !important;
        }*/
        /*.dataTables_filter {
            float: right !important;
        }*/
    </style>
@stop